SELECT VDIC_HGI_CENSO.CD_LEITO, 
       VDIC_HGI_CENSO.DS_ENFERMARIA, 
       VDIC_HGI_CENSO.LEITO, 
       VDIC_HGI_CENSO.EXTRA, 
       VDIC_HGI_CENSO.OCUPACAO, 
       VDIC_HGI_CENSO.UNIDADE, 
       VDIC_HGI_CENSO.CD_ATENDIMENTO, 
       VDIC_HGI_CENSO.DT_ATENDIMENTO, 
       VDIC_HGI_CENSO.PACIENTE, 
       VDIC_HGI_CENSO.IDADE, 
       VDIC_HGI_CENSO.DIAGNOSTICO, 
       VDIC_HGI_CENSO.ORIGEM, 
       VDIC_HGI_CENSO.CD_UNID_INT, 
       VDIC_HGI_CENSO.DS_RESUMO
FROM DBAMV.VDIC_HGI_CENSO VDIC_HGI_CENSO
WHERE 
      (VDIC_HGI_CENSO.UNIDADE = 'SEMI-INTESIVA')
      AND VDIC_HGI_CENSO.EXTRA IS NOT NULL
      -- AND VDIC_HGI_CENSO.EXTRA = 'S' OR VDIC_HGI_CENSO.EXTRA = 'N'
      -- AND VDIC_HGI_CENSO.OCUPACAO IS NOT NULL
ORDER BY VDIC_HGI_CENSO.CD_UNID_INT, 
         VDIC_HGI_CENSO.DS_ENFERMARIA, 
         VDIC_HGI_CENSO.LEITO