CREATE OR REPLACE VIEW v_duplicata_duplicada (
  cd_con_pag,
  campo4,
  campo5,
  campo7,
  campo8,
  campo10,
  campo11,
  campo15
) AS
(SELECT CON_PAG.cd_con_pag
,LPAD(NVL(DE_PARA_FORNECEDOR.CD_FORNECEDOR_PARA,'0' ),11,'0') CAMPO4
,LPAD(NVL(REPLACE(ENT_PRO.NR_DOCUMENTO,'.',''),'0' ),11,'0') CAMPO5
,LPAD(NVL(ITCON_PAG.NR_PARCELA,'0' ),3,'0') CAMPO7
,RPAD(NVL(TO_CHAR(REPLACE(ENT_PRO.NR_DOCUMENTO,'.',''))||'-'||TO_CHAR(ITCON_PAG.NR_PARCELA),' ' ),15,' ') CAMPO8
,RPAD(NVL(TO_CHAR(ITCON_PAG.DT_VENCIMENTO,'DD/MM/YYYY'),' ' ),10,' ') CAMPO10
,LPAD(NVL(TO_CHAR(ITCON_PAG.VL_DUPLICATA,'999,999,999,999.00'),'0' ),20,'0') CAMPO11
,RPAD(NVL(TO_CHAR(ENT_PRO.DT_ENTRADA,'DD/MM/YYYY'),' ' ),10,' ') CAMPO15
FROM DBAMV.ENT_PRO ENT_PRO
,DBAMV.CON_PAG CON_PAG
,DBAMV.ITCON_PAG ITCON_PAG
,DBAMV.DE_PARA_FORNECEDOR DE_PARA_FORNECEDOR
WHERE ENT_PRO.CD_CON_PAG=CON_PAG.CD_CON_PAG
AND ENT_PRO.CD_FORNECEDOR=DE_PARA_FORNECEDOR.CD_FORNECEDOR_DE(+)
AND CON_PAG.CD_CON_PAG=ITCON_PAG.CD_CON_PAG
GROUP BY CON_PAG.cd_con_pag
,LPAD(NVL(DE_PARA_FORNECEDOR.CD_FORNECEDOR_PARA,'0' ),11,'0')
,LPAD(NVL(REPLACE(ENT_PRO.NR_DOCUMENTO,'.',''),'0' ),11,'0')
,LPAD(NVL(ITCON_PAG.NR_PARCELA,'0' ),3,'0')
,RPAD(NVL(TO_CHAR(REPLACE(ENT_PRO.NR_DOCUMENTO,'.',''))||'-'||TO_CHAR(ITCON_PAG.NR_PARCELA),' ' ),15,' ')
,RPAD(NVL(TO_CHAR(ITCON_PAG.DT_VENCIMENTO,'DD/MM/YYYY'),' ' ),10,' ')
,LPAD(NVL(TO_CHAR(ITCON_PAG.VL_DUPLICATA,'999,999,999,999.00'),'0' ),20,'0')
,RPAD(NVL(TO_CHAR(ENT_PRO.DT_ENTRADA,'DD/MM/YYYY'),' ' ),10,' '))
/

GRANT DELETE,INSERT,SELECT,UPDATE ON v_duplicata_duplicada TO dbadw;
GRANT DELETE,INSERT,SELECT,UPDATE ON v_duplicata_duplicada TO dbaps;
GRANT DELETE,INSERT,SELECT,UPDATE ON v_duplicata_duplicada TO dbasgu;
GRANT DELETE,INSERT,SELECT,UPDATE ON v_duplicata_duplicada TO mv2000;
GRANT DELETE,INSERT,SELECT,UPDATE ON v_duplicata_duplicada TO mvintegra;
