CREATE OR REPLACE VIEW v_item_duplicado (
  cd_con_pag,
  campo2,
  campo7,
  campo8,
  campo9,
  campo13,
  campo15,
  campo26,
  campo28,
  campo33,
  campo40,
  campo43,
  campo48,
  campo50,
  campo51,
  campo52,
  campo53,
  campo57,
  campo62,
  campo91,
  campo93,
  campo94,
  campo97,
  campo98,
  campo101
) AS
(SELECT CON_PAG.CD_CON_PAG
       ,LPAD(NVL(DE_PARA_FORNECEDOR.CD_FORNECEDOR_PARA,'0' ),6,'0') CAMPO2
       ,LPAD(NVL(SUBSTR(CD_ITENT_PRO,(LENGTH(CD_ITENT_PRO)-1),3),'0' ),3,'0') CAMPO7
       ,RPAD(NVL(DECODE(CIDADE.CD_UF,'SP','1556A','2556A'),' ' ),5,' ') CAMPO8
       ,LPAD(NVL(ENT_PRO.CD_CFOP,'0' ),5,'0') CAMPO9
       ,RPAD(NVL(TO_CHAR(LPAD(DE_PARA_PRODUTO.CD_PRODUTO_PARA,6,0)),' ' ),14,' ') CAMPO13
       ,LPAD(NVL(DE_PARA_PRODUTO.CD_ESPECIE_PARA,'0' ),6,'0') CAMPO15
       ,LPAD(NVL(ESTOQUE.CD_ESTOQUE,'0' ),10,'0') CAMPO26
       ,RPAD(NVL(TO_CHAR(ITENT_PRO.QT_ENTRADA,'99999999999.90000'),' ' ),17,' ') CAMPO28
       ,RPAD(NVL(TO_CHAR(ITENT_PRO.QT_ENTRADA,'99999999999.90000'),' ' ),17,' ') CAMPO33
       ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_UNITARIO,'99999999999.90000'),'0' ),17,'0') CAMPO40
       ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_PERCENTUAL_DESCONTO,'999.90'),'0' ),6,'0') CAMPO43
       ,LPAD(NVL(TO_CHAR(ENT_PRO.VL_PERCENTUAL_ICMS,'999.90'),'0' ),6,'0') CAMPO48
       ,LPAD(NVL(DE_PARA_CONTABIL.CONTA_REDUZIDA_PARA,'0' ),9,'0') CAMPO50
       ,LPAD(NVL(DE_PARA_CONTABIL_1.CONTA_REDUZIDA_PARA,'0' ),9,'0') CAMPO51
       ,RPAD(NVL(DE_PARA_CENTRO_CUSTO.CENTRO_CUSTO_PARA,' ' ),9,' ') CAMPO52
       ,LPAD(NVL(TO_CHAR(ENT_PRO.VL_FRETE,'99,999,999.90'),'0' ),14,'0') CAMPO53
       ,LPAD(NVL(TO_CHAR(ENT_PRO.VL_OUTROS,'99,999,999.90'),'0' ),14,'0') CAMPO57
       ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_TOTAL,'99,999,999.90'),'0' ),14,'0') CAMPO62
       ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_TOTAL,'99,999,999.90'),'0' ),14,'0') CAMPO91
       ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_TOTAL,'9,999,999,999.90'),'0' ),17,'0') CAMPO93
       ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_TOTAL,'9,999,999,999.90'),'0' ),17,'0') CAMPO94
       ,RPAD(NVL(ENT_PRO.NR_SERIE,' ' ),3,' ') CAMPO97
       ,RPAD(NVL(REPLACE(ENT_PRO.NR_DOCUMENTO,'.',''),' ' ),7,' ') CAMPO98
       ,LPAD(NVL(TO_NUMBER(REPLACE(ENT_PRO.NR_DOCUMENTO,'.','')),'0' ),11,'0') CAMPO101
  FROM DBAMV.CON_PAG CON_PAG,DBAMV.ENT_PRO ENT_PRO
      ,DBAMV.ITENT_PRO ITENT_PRO
      ,DBAMV.DE_PARA_PRODUTO DE_PARA_PRODUTO
      ,DBAMV.DE_PARA_CONTABIL DE_PARA_CONTABIL
      ,DBAMV.ESTOQUE ESTOQUE
      ,DBAMV.SETOR SETOR
      ,DBAMV.DE_PARA_CENTRO_CUSTO DE_PARA_CENTRO_CUSTO
      ,DBAMV.DE_PARA_CONTABIL DE_PARA_CONTABIL_1
      ,DBAMV.DE_PARA_FORNECEDOR DE_PARA_FORNECEDOR
      ,DBAMV.CIDADE CIDADE
      ,DBAMV.FORNECEDOR FORNECEDOR
WHERE CON_PAG.CD_REDUZIDO=DE_PARA_CONTABIL.CD_REDUZIDO_DE(+)
AND ENT_PRO.NR_DOCUMENTO=CON_PAG.NR_DOCUMENTO
AND ENT_PRO.CD_FORNECEDOR=CON_PAG.CD_FORNECEDOR
AND ENT_PRO.CD_ESTOQUE=ESTOQUE.CD_ESTOQUE
AND ENT_PRO.CD_FORNECEDOR=DE_PARA_FORNECEDOR.CD_FORNECEDOR_DE(+)
AND ITENT_PRO.CD_PRODUTO=DE_PARA_PRODUTO.CD_PRODUTO_DE(+)
AND ESTOQUE.CD_SETOR=SETOR.CD_SETOR
AND ESTOQUE.CD_REDUZIDO_DEBITO=DE_PARA_CONTABIL_1.CONTA_REDUZIDA_PARA(+)
AND SETOR.CD_SETOR=DE_PARA_CENTRO_CUSTO.CD_SETOR_DE(+)
AND ENT_PRO.CD_FORNECEDOR=FORNECEDOR.CD_FORNECEDOR
AND FORNECEDOR.CD_CIDADE=CIDADE.CD_CIDADE
AND ENT_PRO.CD_ENT_PRO=ITENT_PRO.CD_ENT_PRO
group by CON_PAG.CD_CON_PAG
   ,LPAD(NVL(DE_PARA_FORNECEDOR.CD_FORNECEDOR_PARA,'0' ),6,'0')
   ,LPAD(NVL(SUBSTR(CD_ITENT_PRO,(LENGTH(CD_ITENT_PRO)-1),3),'0' ),3,'0')
   ,RPAD(NVL(DECODE(CIDADE.CD_UF,'SP','1556A','2556A'),' ' ),5,' ')
   ,LPAD(NVL(ENT_PRO.CD_CFOP,'0' ),5,'0')
   ,RPAD(NVL(TO_CHAR(LPAD(DE_PARA_PRODUTO.CD_PRODUTO_PARA,6,0)),' ' ),14,' ')
   ,LPAD(NVL(DE_PARA_PRODUTO.CD_ESPECIE_PARA,'0' ),6,'0')
   ,LPAD(NVL(ESTOQUE.CD_ESTOQUE,'0' ),10,'0')
   ,RPAD(NVL(TO_CHAR(ITENT_PRO.QT_ENTRADA,'99999999999.90000'),' ' ),17,' ')
   ,RPAD(NVL(TO_CHAR(ITENT_PRO.QT_ENTRADA,'99999999999.90000'),' ' ),17,' ')
   ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_UNITARIO,'99999999999.90000'),'0' ),17,'0')
   ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_PERCENTUAL_DESCONTO,'999.90'),'0' ),6,'0')
   ,LPAD(NVL(TO_CHAR(ENT_PRO.VL_PERCENTUAL_ICMS,'999.90'),'0' ),6,'0')
   ,LPAD(NVL(DE_PARA_CONTABIL.CONTA_REDUZIDA_PARA,'0' ),9,'0')
   ,LPAD(NVL(DE_PARA_CONTABIL_1.CONTA_REDUZIDA_PARA,'0' ),9,'0')
   ,RPAD(NVL(DE_PARA_CENTRO_CUSTO.CENTRO_CUSTO_PARA,' ' ),9,' ')
   ,LPAD(NVL(TO_CHAR(ENT_PRO.VL_FRETE,'99,999,999.90'),'0' ),14,'0')
   ,LPAD(NVL(TO_CHAR(ENT_PRO.VL_OUTROS,'99,999,999.90'),'0' ),14,'0')
   ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_TOTAL,'99,999,999.90'),'0' ),14,'0')
   ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_TOTAL,'99,999,999.90'),'0' ),14,'0')
   ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_TOTAL,'9,999,999,999.90'),'0' ),17,'0')
   ,LPAD(NVL(TO_CHAR(ITENT_PRO.VL_TOTAL,'9,999,999,999.90'),'0' ),17,'0')
   ,RPAD(NVL(ENT_PRO.NR_SERIE,' ' ),3,' ')
   ,RPAD(NVL(REPLACE(ENT_PRO.NR_DOCUMENTO,'.',''),' ' ),7,' ')
   ,LPAD(NVL(TO_NUMBER(REPLACE(ENT_PRO.NR_DOCUMENTO,'.','')),'0' ),11,'0'))
/

GRANT DELETE,INSERT,SELECT,UPDATE ON v_item_duplicado TO dbadw;
GRANT DELETE,INSERT,SELECT,UPDATE ON v_item_duplicado TO dbaps;
GRANT DELETE,INSERT,SELECT,UPDATE ON v_item_duplicado TO dbasgu;
GRANT DELETE,INSERT,SELECT,UPDATE ON v_item_duplicado TO mv2000;
GRANT DELETE,INSERT,SELECT,UPDATE ON v_item_duplicado TO mvintegra;
